---
title: "Read synthesis files"
author: "Jens Daniel M체ller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r libraries, include=FALSE}

library(tidyverse)
library(sp)

```

```{r set_theme, include=FALSE}

theme_set(theme_bw())

```


# Set path

```{r set_path}

path_SOCAT <- "/nfs/kryo/work/updata/SOCAT/"
print(path_SOCAT)

```


# Read files

```{r read_files}

SOCAT_Finn <-
  read_csv(paste0(path_SOCAT, "SOCATv2021_Baltic_Finnmaid.csv"))


SOCAT_Finn <- SOCAT_Finn %>% 
  drop_na()

```


# Track

```{r track_map}

baltic_map <-
  ggplot(data = map_data("world"),
         aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), fill = "grey80", colour = "black") +
  coord_map("ortho", xlim = c(11, 29), ylim = c(54, 61))

baltic_map <-
ggplot(data = map_data("world"),
         aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), fill = "grey80", colour = "black") +
  coord_quickmap(xlim = c(11, 29), ylim = c(54, 61))

baltic_map +
  geom_bin2d(data = SOCAT_Finn,
             aes(lon, lat),
             binwidth = 0.1) +
  scale_fill_viridis_c() +
  labs(title = "Observations on 0.1째 x 0.1째 grid")


```

# Monthly climatologies

```{r climatologies}

vars <- c("fCO2", "SST", "sal")

for (i_var in vars) {
  # i_var <- vars[1]
  
  print(
  SOCAT_Finn %>%
    ggplot(aes(mon, lat, z = !!sym(i_var))) +
    stat_summary_2d() +
    scale_fill_viridis_c(name = i_var) +
    coord_cartesian(expand = 0)
  )
  
}



```

# Regional time series

## Determine routes

```{r route_determination}

# determine cruises on Gydnia (G) route
cruises_G <- SOCAT_Finn %>%
  mutate(
    region = point.in.polygon(
      point.x = lon,
      point.y = lat,
      pol.x = c(16,20.5,20),
      pol.y = c(55,57,54)
    )) %>%  
  filter(region == 1) %>% 
  distinct(cruise) %>% 
  pull()

# determine cruises on Eastern (E) route around Gotland
cruises_E <- SOCAT_Finn %>%
  mutate(
    region = point.in.polygon(
      point.x = lon,
      point.y = lat,
      pol.x = c(18,18,19.5,20.5,19),
      pol.y = c(56,57,58,58,56.5)
    )) %>%  
  filter(region == 1) %>% 
  distinct(cruise) %>% 
  pull()

# determine cruises to St. Petersburg (P)
cruises_P <- SOCAT_Finn %>% 
  filter(lon > 29) %>% 
  distinct(cruise) %>% 
  pull()

# assign route labels
SOCAT_Finn <- SOCAT_Finn %>% 
  mutate(route = "W",
         route = if_else(cruise %in% cruises_E, "E", route),
         route = if_else(cruise %in% cruises_G, "G", route),
         route = if_else(cruise %in% cruises_P, "P", route))

# cut into lat lon grid
SOCAT_Finn <- SOCAT_Finn %>%
  mutate(lat_grid = as.numeric(as.character(cut(
    lat, seq(50, 65, 0.1), seq(50.05, 64.95, 0.1)
  ))),
  lon_grid = as.numeric(as.character(cut(
    lon, seq(10, 35, 0.1), seq(10.05, 34.95, 0.1)
  ))))

SOCAT_Finn_routes <- SOCAT_Finn %>% 
  count(lat_grid, lon_grid, route)

baltic_map +
  geom_raster(data = SOCAT_Finn_routes %>% select(-route),
              aes(lon_grid, lat_grid), fill = "grey80") +
  geom_raster(data = SOCAT_Finn_routes,
              aes(lon_grid, lat_grid), fill = "red") +
  facet_wrap( ~ route)

```

## Assign region

```{r region_determination}

# Assign regions according to Schneider and M체ller (2018)
SOCAT_Finn <- SOCAT_Finn %>% 
  mutate(region = case_when(
    lon>12 & lon<12.6 ~ "1.MEB",
    lon>13.1 & lon<14.3 ~ "2.ARK",
    lat>57.5 & lat<58.5 & route %in% c("E", "G") ~ "4.EGS",
    lat>56.8 & lat<57.5 & route=="W" ~ "3.WGS",
    lat>58.5 & lat<59 & lon>20 ~ "5.NGS",
    lon>22 & lon<24 ~ "6.WGF",
    lon>24 & lon<24.5 ~ "7.HGF")) %>% 
  filter(!is.na(region))


```

## Plot time series

```{r regional_time_series}

# calculate mean values for each crossing of each region
SOCAT_Finn_region <- SOCAT_Finn %>% 
  group_by(region, cruise) %>% 
  summarise(date_time = mean(date_time),
            fCO2 = mean(fCO2),
            SST = mean(SST),
            sal = mean(sal)) %>% 
  ungroup()

# convert to long format
SOCAT_Finn_region_long <- SOCAT_Finn_region %>% 
  pivot_longer(fCO2:sal,
               names_to = "parameter",
               values_to = "value")

# plot time series
SOCAT_Finn_region_long %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(date_time, value)) +
      geom_point(size = 0.5) +
      scale_x_datetime(breaks = "2 years",
                       date_labels = "%Y") +
      labs(y = unique(.x$parameter)) +
      facet_grid(region ~ .)
  )


```



# Write time series file

```{r write_file}

SOCAT_Finn_region %>% 
  select(-cruise) %>% 
  write_csv(here::here("data/", "Baltic_regions_fCO2_time_series.csv"))


```

