---
title: "Read Finnmaid data from synthesis files"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r libraries, echo=FALSE}
library(tidyverse)
```


# Set path

```{r set_path}
path_SOCAT <- "/nfs/kryo/work/updata/SOCAT/"
print(path_SOCAT)
```


# Read files

```{r read_files}

# define file names
file_all <- "SOCATv2021.tsv"
file_FlagE <- "SOCATv2021_FlagE.tsv"

# # create file with SOCAT header
# header <- read_lines(
#   file = paste0(path_SOCAT, file_all),
#   n_max = 7000
# )
# 
# header %>% 
#   write_lines(here::here("data/",
#                          "SOCATv2021_header.txt"))

# Determine DOI with Finnmaid/Finnpartner data in regular synthesis file
# and read only those data

meta <- read_delim(
  file = paste0(path_SOCAT, file_all),
  "\t",
  escape_double = FALSE,
  trim_ws = TRUE,
  skip = 4,
  n_max = 6564
)

meta <- meta %>%
  filter(str_detect(`Platform Name`, "Finn"))

Finn_Expocodes <- meta$Expocode

f_subset <-
  function(x, pos) subset(x, Expocode %in% Finn_Expocodes)

SOCAT_Finn <-
  read_tsv_chunked(
    file = paste0(path_SOCAT, file_all),
    skip = 6623,
    DataFrameCallback$new(f_subset),
    chunk_size = 100000
  )

rm(meta, Finn_Expocodes)

# Determine DOI with Finnmaid/Finnpartner data in flag E synthesis file
# and read only those data

meta <- read_delim(
  file = paste0(path_SOCAT, file_FlagE),
  "\t",
  escape_double = FALSE,
  trim_ws = TRUE,
  skip = 4,
  n_max = 194
)

meta <- meta %>%
  filter(`Platform Name` %in% c("Finnmaid", "VOS Finnpartner"))

Finn_Expocodes <- meta$Expocode

SOCAT_Finn_E <-
  read_tsv_chunked(
    file = paste0(path_SOCAT, file_FlagE),
    skip = 251,
    DataFrameCallback$new(f_subset),
    chunk_size = 100000
  )

rm(f_subset, meta, Finn_Expocodes)


# Merge data from regular and flag E synthesis file

SOCAT_Finn <-
  bind_rows(SOCAT_Finn %>% mutate(across(yr:ss, as.character)),
            SOCAT_Finn_E %>% mutate(across(yr:ss, as.character)))

rm(SOCAT_Finn_E)

# rename and subset columns

SOCAT_Finn <- SOCAT_Finn %>% 
  rename("lon" = "longitude [dec.deg.E]",
         "lat" = "latitude [dec.deg.N]",
         "fCO2" = "fCO2rec [uatm]",
         "SST" = "SST [deg.C]") %>% 
  mutate(date_time = lubridate::ymd_hms(paste(yr, mon, day, hh, mm, ss))) %>% 
  select(date_time, yr, mon, lon, lat, sal, SST, fCO2)


# Plot time series to check read-in procedure

SOCAT_Finn %>% 
  filter(lat > 59, lat < 59.05) %>% 
  ggplot(aes(date_time, fCO2, col=SST))+
  geom_point()+
  scale_color_viridis_c()+
  labs(x="", y="fCO2", title = "Finnpartner / Finnmaid data",
      subtitle = "Subsets from SOCATv2021 incl Flag E  | Lat range: 59-59.05N")+
  theme_bw()



```

# Identify cruises

In order to identify cruises, we determine a threshold for the time lag between observations. 

```{r cruise_identification, fig.asp=0.5}

for (time_lag_limit in seq(0.2, 20, 0.1)*60^2) {
  
  # print(time_lag_limit/60^2)
  
  SOCAT_Finn <- SOCAT_Finn %>%
  arrange(date_time) %>%
  mutate(cruise = cumsum(c(TRUE, diff(date_time) >= time_lag_limit)))
  
  cruise_duration <- SOCAT_Finn %>% 
    group_by(cruise) %>% 
    summarise(cruise_duration = 
                as.numeric(difftime(max(date_time), min(date_time), units = "hours"))) %>% 
    summarise(min_duration = min(cruise_duration),
              max_duration = max(cruise_duration))

  cruise_counts_temp <- bind_cols( 
  time_lag_limit = time_lag_limit/60^2,
  n_cruises = max(SOCAT_Finn$cruise)
  )
  
  cruise_counts_temp <- bind_cols(
    cruise_counts_temp,
    cruise_duration
  )
  
  if (exists("cruise_counts")) {
    cruise_counts <- bind_rows(cruise_counts, cruise_counts_temp)
  }
  
  if (!exists("cruise_counts")) {
    cruise_counts <- cruise_counts_temp
  }

  
}

cruise_counts %>% 
  ggplot(aes(time_lag_limit, n_cruises)) +
  geom_path() +
  geom_point()

cruise_counts %>% 
  ggplot(aes(time_lag_limit, max_duration)) +
  geom_path() +
  geom_point() +
  coord_cartesian(ylim = c(0,100))

cruise_counts %>%
  ggplot(aes(time_lag_limit, min_duration)) +
  geom_path() +
  geom_point() +
  coord_cartesian(ylim = c(0, 1))

rm(cruise_counts, cruise_counts_temp, cruise_duration)


for (time_lag_limit in seq(2, 8, 2)*60^2) {
  
  # print(time_lag_limit/60^2)
  
  SOCAT_Finn <- SOCAT_Finn %>%
  arrange(date_time) %>%
  mutate(cruise = cumsum(c(TRUE, diff(date_time) >= time_lag_limit)))
  
  cruise_duration <- SOCAT_Finn %>% 
    group_by(cruise) %>% 
    summarise(cruise_duration = 
                as.numeric(difftime(max(date_time), min(date_time), units = "hours")))

  cruise_counts_temp <- bind_cols( 
  time_lag_limit = time_lag_limit/60^2,
  n_cruises = max(SOCAT_Finn$cruise)
  )
  
  cruise_counts_temp <- bind_cols(
    cruise_counts_temp,
    cruise_duration
  )
  
  if (exists("cruise_counts")) {
    cruise_counts <- bind_rows(cruise_counts, cruise_counts_temp)
  }
  
  if (!exists("cruise_counts")) {
    cruise_counts <- cruise_counts_temp
  }

  
}



cruise_counts %>% 
  ggplot(aes(as.factor(time_lag_limit), cruise_duration)) +
  geom_violin()


# set time lag to cut cruises

time_lag_limit <- 5*60^2
print(paste("Choosen time lag [hrs]:", time_lag_limit/60^2))


SOCAT_Finn <- SOCAT_Finn %>%
  arrange(date_time) %>%
  mutate(cruise = cumsum(c(TRUE, diff(date_time) >= time_lag_limit)))

cruise_duration <- SOCAT_Finn %>%
  group_by(cruise) %>%
  summarise(cruise_duration =
              as.numeric(difftime(max(date_time), min(date_time), units = "hours")))

SOCAT_Finn <- SOCAT_Finn %>%
  group_by(cruise) %>%
  mutate(cruise_duration =
              as.numeric(difftime(max(date_time), min(date_time), units = "hours")))


cruise_duration %>% 
  ggplot(aes(cruise_duration)) +
  geom_histogram()

SOCAT_Finn %>% 
  ggplot(aes(cruise_duration)) +
  geom_histogram()

# filter very short cruises
cruise_duration_limit <- 2
print(paste("Cruises shorten than this were removed [hrs]:", cruise_duration_limit))

SOCAT_Finn %>% filter(cruise_duration < cruise_duration_limit) %>% 
  count(cruise)

SOCAT_Finn <- SOCAT_Finn %>% 
  filter(cruise_duration >= cruise_duration_limit) %>% 
  select(cruise, date_time, yr, mon, lon, lat, sal, SST, fCO2)

```


# Write summary file


```{r write_file}

SOCAT_Finn %>%
  write_csv(paste0(path_SOCAT, "SOCATv2021_Baltic_Finnmaid.csv"))


```

